// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: opinit/ophost/v1/types.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types1 "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ChainType defines the type of chain.
type BatchInfo_ChainType int32

const (
	// Unspecified chain type.
	BatchInfo_UNSPECIFIED BatchInfo_ChainType = 0
	// The chain type of the initia chain.
	BatchInfo_INITIA BatchInfo_ChainType = 1
	// The chain type of the celestia chain.
	BatchInfo_CELESTIA BatchInfo_ChainType = 2
)

var BatchInfo_ChainType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "INITIA",
	2: "CELESTIA",
}

var BatchInfo_ChainType_value = map[string]int32{
	"UNSPECIFIED": 0,
	"INITIA":      1,
	"CELESTIA":    2,
}

func (x BatchInfo_ChainType) String() string {
	return proto.EnumName(BatchInfo_ChainType_name, int32(x))
}

func (BatchInfo_ChainType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_29cadbd84ee898dd, []int{2, 0}
}

// Params defines the set of ophost parameters.
type Params struct {
	// The amount to be paid by l2 creator.
	RegistrationFee github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=registration_fee,json=registrationFee,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"registration_fee"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_29cadbd84ee898dd, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// BridgeConfig defines the set of bridge config.
type BridgeConfig struct {
	// The address of the challenger.
	Challenger string `protobuf:"bytes,1,opt,name=challenger,proto3" json:"challenger,omitempty"`
	// The address of the proposer.
	Proposer string `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty"`
	// The information about batch submission.
	BatchInfo BatchInfo `protobuf:"bytes,3,opt,name=batch_info,json=batchInfo,proto3" json:"batch_info"`
	// The time interval at which checkpoints must be submitted.
	// NOTE: this param is currently not used, but will be used for challenge in future.
	SubmissionInterval time.Duration `protobuf:"bytes,4,opt,name=submission_interval,json=submissionInterval,proto3,stdduration" json:"submission_interval,omitempty"`
	// The minimum time duration that must elapse before a withdrawal can be finalized.
	FinalizationPeriod time.Duration `protobuf:"bytes,5,opt,name=finalization_period,json=finalizationPeriod,proto3,stdduration" json:"finalization_period,omitempty"`
	// The the first l2 block will be recorded on l1.
	SubmissionStartHeight uint64 `protobuf:"varint,6,opt,name=submission_start_height,json=submissionStartHeight,proto3" json:"submission_start_height,omitempty"`
	// oracle_enabled is a flag to enable oracle.
	OracleEnabled bool `protobuf:"varint,7,opt,name=oracle_enabled,json=oracleEnabled,proto3" json:"oracle_enabled,omitempty"`
	// Normally it is IBC channelID for permissioned IBC relayer.
	Metadata []byte `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Optional config for Fast Bridge
	FastBridgeConfig *FastBridgeConfig `protobuf:"bytes,9,opt,name=fast_bridge_config,json=fastBridgeConfig,proto3" json:"fast_bridge_config,omitempty"`
}

func (m *BridgeConfig) Reset()         { *m = BridgeConfig{} }
func (m *BridgeConfig) String() string { return proto.CompactTextString(m) }
func (*BridgeConfig) ProtoMessage()    {}
func (*BridgeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_29cadbd84ee898dd, []int{1}
}
func (m *BridgeConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BridgeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BridgeConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BridgeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeConfig.Merge(m, src)
}
func (m *BridgeConfig) XXX_Size() int {
	return m.Size()
}
func (m *BridgeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeConfig proto.InternalMessageInfo

// BatchInfo defines the set of batch information.
type BatchInfo struct {
	// The address of the batch submitter.
	Submitter string `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	// The target chain type.
	ChainType BatchInfo_ChainType `protobuf:"varint,2,opt,name=chain_type,json=chainType,proto3,enum=opinit.ophost.v1.BatchInfo_ChainType" json:"chain_type,omitempty"`
}

func (m *BatchInfo) Reset()         { *m = BatchInfo{} }
func (m *BatchInfo) String() string { return proto.CompactTextString(m) }
func (*BatchInfo) ProtoMessage()    {}
func (*BatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_29cadbd84ee898dd, []int{2}
}
func (m *BatchInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchInfo.Merge(m, src)
}
func (m *BatchInfo) XXX_Size() int {
	return m.Size()
}
func (m *BatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BatchInfo proto.InternalMessageInfo

// TokenPair defines l1 and l2 token pair
type TokenPair struct {
	L1Denom string `protobuf:"bytes,1,opt,name=l1_denom,json=l1Denom,proto3" json:"l1_denom,omitempty"`
	L2Denom string `protobuf:"bytes,2,opt,name=l2_denom,json=l2Denom,proto3" json:"l2_denom,omitempty"`
}

func (m *TokenPair) Reset()         { *m = TokenPair{} }
func (m *TokenPair) String() string { return proto.CompactTextString(m) }
func (*TokenPair) ProtoMessage()    {}
func (*TokenPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_29cadbd84ee898dd, []int{3}
}
func (m *TokenPair) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TokenPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TokenPair.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TokenPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenPair.Merge(m, src)
}
func (m *TokenPair) XXX_Size() int {
	return m.Size()
}
func (m *TokenPair) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenPair.DiscardUnknown(m)
}

var xxx_messageInfo_TokenPair proto.InternalMessageInfo

// Output is a l2 block submitted by proposer.
type Output struct {
	// Hash of the l2 output.
	OutputRoot []byte `protobuf:"bytes,1,opt,name=output_root,json=outputRoot,proto3" json:"output_root,omitempty"`
	// The l1 block number that the output root was submitted in.
	L1BlockNumber uint64 `protobuf:"varint,2,opt,name=l1_block_number,json=l1BlockNumber,proto3" json:"l1_block_number,omitempty"`
	// Timestamp of the l1 block that the output root was submitted in.
	L1BlockTime time.Time `protobuf:"bytes,3,opt,name=l1_block_time,json=l1BlockTime,proto3,stdtime" json:"l1_block_time"`
	// The l2 block number that the output root was submitted in.
	L2BlockNumber uint64 `protobuf:"varint,4,opt,name=l2_block_number,json=l2BlockNumber,proto3" json:"l2_block_number,omitempty"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_29cadbd84ee898dd, []int{4}
}
func (m *Output) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Output.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return m.Size()
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

// BatchInfoWithOutput defines the batch information with output.
type BatchInfoWithOutput struct {
	BatchInfo BatchInfo `protobuf:"bytes,1,opt,name=batch_info,json=batchInfo,proto3" json:"batch_info"`
	Output    Output    `protobuf:"bytes,2,opt,name=output,proto3" json:"output"`
}

func (m *BatchInfoWithOutput) Reset()         { *m = BatchInfoWithOutput{} }
func (m *BatchInfoWithOutput) String() string { return proto.CompactTextString(m) }
func (*BatchInfoWithOutput) ProtoMessage()    {}
func (*BatchInfoWithOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_29cadbd84ee898dd, []int{5}
}
func (m *BatchInfoWithOutput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BatchInfoWithOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BatchInfoWithOutput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BatchInfoWithOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchInfoWithOutput.Merge(m, src)
}
func (m *BatchInfoWithOutput) XXX_Size() int {
	return m.Size()
}
func (m *BatchInfoWithOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchInfoWithOutput.DiscardUnknown(m)
}

var xxx_messageInfo_BatchInfoWithOutput proto.InternalMessageInfo

// FastBridgeConfig defines validator set and threshold for fast withdrawals.
type FastBridgeConfig struct {
	// Verifier set authorized to sign withdrawals
	Verifiers []FastBridgeVerifier `protobuf:"bytes,1,rep,name=verifiers,proto3" json:"verifiers"`
	// Number of required validator signatures to finalize a withdrawal
	Threshold uint32 `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// Maximum percentage of the bridge balance that can be withdrawn within the recovery window (e.g., "0.2" = 20%)
	MaxRate string `protobuf:"bytes,3,opt,name=max_rate,json=maxRate,proto3" json:"max_rate,omitempty"`
	// Time duration (in seconds) over which the max_rate is applied (e.g., 86400 = 24h)
	RecoveryWindow uint64 `protobuf:"varint,4,opt,name=recovery_window,json=recoveryWindow,proto3" json:"recovery_window,omitempty"`
	// Fast bridge fee. Must be uinit on L1, but op-bridged init on L2
	BaseFee types.Coin `protobuf:"bytes,5,opt,name=base_fee,json=baseFee,proto3" json:"base_fee" yaml:"base_fee"`
}

func (m *FastBridgeConfig) Reset()         { *m = FastBridgeConfig{} }
func (m *FastBridgeConfig) String() string { return proto.CompactTextString(m) }
func (*FastBridgeConfig) ProtoMessage()    {}
func (*FastBridgeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_29cadbd84ee898dd, []int{6}
}
func (m *FastBridgeConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FastBridgeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FastBridgeConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FastBridgeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastBridgeConfig.Merge(m, src)
}
func (m *FastBridgeConfig) XXX_Size() int {
	return m.Size()
}
func (m *FastBridgeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FastBridgeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FastBridgeConfig proto.InternalMessageInfo

// FastBridgeValidator represents a multisig validator.
type FastBridgeVerifier struct {
	Address string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Pubkey  *types1.Any `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (m *FastBridgeVerifier) Reset()         { *m = FastBridgeVerifier{} }
func (m *FastBridgeVerifier) String() string { return proto.CompactTextString(m) }
func (*FastBridgeVerifier) ProtoMessage()    {}
func (*FastBridgeVerifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_29cadbd84ee898dd, []int{7}
}
func (m *FastBridgeVerifier) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FastBridgeVerifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FastBridgeVerifier.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FastBridgeVerifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastBridgeVerifier.Merge(m, src)
}
func (m *FastBridgeVerifier) XXX_Size() int {
	return m.Size()
}
func (m *FastBridgeVerifier) XXX_DiscardUnknown() {
	xxx_messageInfo_FastBridgeVerifier.DiscardUnknown(m)
}

var xxx_messageInfo_FastBridgeVerifier proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("opinit.ophost.v1.BatchInfo_ChainType", BatchInfo_ChainType_name, BatchInfo_ChainType_value)
	proto.RegisterType((*Params)(nil), "opinit.ophost.v1.Params")
	proto.RegisterType((*BridgeConfig)(nil), "opinit.ophost.v1.BridgeConfig")
	proto.RegisterType((*BatchInfo)(nil), "opinit.ophost.v1.BatchInfo")
	proto.RegisterType((*TokenPair)(nil), "opinit.ophost.v1.TokenPair")
	proto.RegisterType((*Output)(nil), "opinit.ophost.v1.Output")
	proto.RegisterType((*BatchInfoWithOutput)(nil), "opinit.ophost.v1.BatchInfoWithOutput")
	proto.RegisterType((*FastBridgeConfig)(nil), "opinit.ophost.v1.FastBridgeConfig")
	proto.RegisterType((*FastBridgeVerifier)(nil), "opinit.ophost.v1.FastBridgeVerifier")
}

func init() { proto.RegisterFile("opinit/ophost/v1/types.proto", fileDescriptor_29cadbd84ee898dd) }

var fileDescriptor_29cadbd84ee898dd = []byte{
	// 1073 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xf6, 0xa6, 0xa9, 0x63, 0x8f, 0xe3, 0xc4, 0x4c, 0x83, 0xd8, 0x84, 0x60, 0x5b, 0x2b, 0x0a,
	0x56, 0x95, 0xac, 0x65, 0x03, 0x15, 0x2a, 0xa7, 0x38, 0x71, 0x84, 0x25, 0x9a, 0x46, 0x9b, 0xd0,
	0x4a, 0x5c, 0x56, 0xb3, 0xf6, 0x78, 0x3d, 0xca, 0xee, 0xce, 0x6a, 0x66, 0xec, 0xc6, 0xe5, 0x1f,
	0x70, 0xca, 0x8d, 0x72, 0x2b, 0x27, 0x2a, 0x4e, 0x3d, 0xf0, 0x23, 0x72, 0xac, 0x38, 0x71, 0x4a,
	0x21, 0x39, 0x14, 0x71, 0xe4, 0x17, 0xa0, 0x99, 0x9d, 0x75, 0x9c, 0x0f, 0x5a, 0xc4, 0x25, 0xd9,
	0x79, 0x9f, 0xe7, 0x9d, 0xf7, 0xeb, 0x99, 0x19, 0x83, 0x55, 0x1a, 0x93, 0x88, 0x88, 0x3a, 0x8d,
	0x07, 0x94, 0x8b, 0xfa, 0xa8, 0x51, 0x17, 0xe3, 0x18, 0x73, 0x3b, 0x66, 0x54, 0x50, 0x58, 0x4a,
	0x50, 0x3b, 0x41, 0xed, 0x51, 0x63, 0xe5, 0x1d, 0x14, 0x92, 0x88, 0xd6, 0xd5, 0xdf, 0x84, 0xb4,
	0x52, 0xee, 0x52, 0x1e, 0x52, 0x5e, 0xf7, 0x10, 0xc7, 0xf5, 0x51, 0xc3, 0xc3, 0x02, 0x35, 0xea,
	0x5d, 0x4a, 0x22, 0x8d, 0x2f, 0x27, 0xb8, 0xab, 0x56, 0xf5, 0x64, 0xa1, 0xa1, 0x25, 0x9f, 0xfa,
	0x34, 0xb1, 0xcb, 0xaf, 0xd4, 0xc1, 0xa7, 0xd4, 0x0f, 0x70, 0x5d, 0xad, 0xbc, 0x61, 0xbf, 0x8e,
	0xa2, 0x71, 0x1a, 0xeb, 0x32, 0xd4, 0x1b, 0x32, 0x24, 0x08, 0x4d, 0x63, 0x55, 0x2e, 0xe3, 0x82,
	0x84, 0x98, 0x0b, 0x14, 0xc6, 0x09, 0xc1, 0xfa, 0xd1, 0x00, 0xd9, 0x5d, 0xc4, 0x50, 0xc8, 0xe1,
	0xb7, 0xa0, 0xc4, 0xb0, 0x4f, 0xb8, 0x48, 0x76, 0x70, 0xfb, 0x18, 0x9b, 0x46, 0xf5, 0x46, 0xad,
	0xd0, 0x5c, 0xb6, 0x75, 0x96, 0xb2, 0x24, 0x5b, 0x97, 0x64, 0x6f, 0x52, 0x12, 0xb5, 0x3e, 0x3b,
	0x3e, 0xa9, 0x64, 0x7e, 0x7e, 0x55, 0xa9, 0xf9, 0x44, 0x0c, 0x86, 0x9e, 0xdd, 0xa5, 0xa1, 0x2e,
	0x49, 0xff, 0x5b, 0xe7, 0xbd, 0x03, 0xdd, 0x43, 0xe9, 0xc0, 0x9f, 0xbf, 0x7e, 0x71, 0xc7, 0x70,
	0x16, 0xa7, 0x23, 0x6d, 0x63, 0x7c, 0x6f, 0xe5, 0xe9, 0xb3, 0x4a, 0xe6, 0xcf, 0x67, 0x15, 0xe3,
	0xbb, 0xd7, 0x2f, 0xee, 0x14, 0x75, 0xf7, 0x93, 0xc4, 0xac, 0xa3, 0x9b, 0x60, 0xbe, 0xc5, 0x48,
	0xcf, 0xc7, 0x9b, 0x34, 0xea, 0x13, 0x1f, 0x7e, 0x0e, 0x40, 0x77, 0x80, 0x82, 0x00, 0x47, 0x3e,
	0x66, 0xa6, 0x51, 0x35, 0x6a, 0xf9, 0x96, 0xf9, 0xeb, 0x2f, 0xeb, 0x4b, 0x3a, 0xcd, 0x8d, 0x5e,
	0x8f, 0x61, 0xce, 0xf7, 0x04, 0x23, 0x91, 0xef, 0x4c, 0x71, 0xe1, 0xa7, 0x20, 0x17, 0x33, 0x1a,
	0x53, 0x8e, 0x99, 0x39, 0xf3, 0x16, 0xbf, 0x09, 0x13, 0xb6, 0x01, 0xf0, 0x90, 0xe8, 0x0e, 0x5c,
	0x12, 0xf5, 0xa9, 0x79, 0xa3, 0x6a, 0xd4, 0x0a, 0xcd, 0xf7, 0xed, 0xcb, 0x5a, 0xb0, 0x5b, 0x92,
	0xd3, 0x89, 0xfa, 0xb4, 0x95, 0x97, 0x5d, 0x49, 0x2a, 0xcd, 0x7b, 0xa9, 0x15, 0x3e, 0x01, 0xb7,
	0xf8, 0xd0, 0x0b, 0x09, 0xe7, 0xb2, 0xbd, 0x24, 0x12, 0x98, 0x8d, 0x50, 0x60, 0xce, 0xaa, 0xfd,
	0x96, 0xed, 0x64, 0x54, 0x76, 0x3a, 0x2a, 0x7b, 0x4b, 0x8f, 0xb2, 0x65, 0xcb, 0xdd, 0xfe, 0x3a,
	0xa9, 0x7c, 0x70, 0x8d, 0xf7, 0x1a, 0x0d, 0x89, 0xc0, 0x61, 0x2c, 0xc6, 0x4f, 0x5f, 0x55, 0x8c,
	0x24, 0x24, 0x3c, 0xe7, 0x75, 0x34, 0x4d, 0xc6, 0xee, 0x93, 0x08, 0x05, 0xe4, 0x49, 0x32, 0xdc,
	0x18, 0x33, 0x42, 0x7b, 0xe6, 0xcd, 0xff, 0x1c, 0xfb, 0x1a, 0xef, 0x6b, 0x63, 0x4f, 0xf3, 0x76,
	0x15, 0x0d, 0xde, 0x05, 0xef, 0x4d, 0x65, 0xce, 0x05, 0x62, 0xc2, 0x1d, 0x60, 0xe2, 0x0f, 0x84,
	0x99, 0xad, 0x1a, 0xb5, 0x59, 0xe7, 0xdd, 0x73, 0x78, 0x4f, 0xa2, 0x5f, 0x2a, 0x10, 0xde, 0x06,
	0x0b, 0x94, 0xa1, 0x6e, 0x80, 0x5d, 0x1c, 0x21, 0x2f, 0xc0, 0x3d, 0x73, 0xae, 0x6a, 0xd4, 0x72,
	0x4e, 0x31, 0xb1, 0xb6, 0x13, 0x23, 0x5c, 0x01, 0xb9, 0x10, 0x0b, 0xd4, 0x43, 0x02, 0x99, 0xb9,
	0xaa, 0x51, 0x9b, 0x77, 0x26, 0x6b, 0xf8, 0x10, 0xc0, 0x3e, 0xe2, 0xc2, 0xf5, 0x94, 0x7c, 0xdc,
	0xae, 0xd2, 0x8f, 0x99, 0x57, 0x55, 0x5b, 0x57, 0x27, 0xb8, 0x8d, 0xb8, 0x98, 0x56, 0x5a, 0x6b,
	0xf6, 0xf8, 0xa4, 0x62, 0x38, 0xa5, 0xfe, 0x25, 0xbb, 0xf5, 0x93, 0x01, 0xf2, 0x93, 0x71, 0xc3,
	0x55, 0x90, 0x57, 0x15, 0x08, 0x91, 0xca, 0xd1, 0x39, 0x37, 0xc0, 0x2d, 0xa5, 0x56, 0x12, 0xb9,
	0xf2, 0x14, 0x28, 0xd5, 0x2d, 0x34, 0x6f, 0xbf, 0x41, 0x3d, 0xf6, 0xa6, 0x64, 0xef, 0x8f, 0x63,
	0xec, 0xe4, 0xbb, 0xe9, 0xa7, 0x75, 0x17, 0xe4, 0x27, 0x76, 0xb8, 0x08, 0x0a, 0x5f, 0xef, 0xec,
	0xed, 0xb6, 0x37, 0x3b, 0xdb, 0x9d, 0xf6, 0x56, 0x29, 0x03, 0x01, 0xc8, 0x76, 0x76, 0x3a, 0xfb,
	0x9d, 0x8d, 0x92, 0x01, 0xe7, 0x41, 0x6e, 0xb3, 0xfd, 0x55, 0x7b, 0x4f, 0xae, 0x66, 0xac, 0x0d,
	0x90, 0xdf, 0xa7, 0x07, 0x38, 0xda, 0x45, 0x84, 0xc1, 0x65, 0x90, 0x0b, 0x1a, 0x6e, 0x0f, 0x47,
	0x34, 0xd4, 0x79, 0xce, 0x05, 0x8d, 0x2d, 0xb9, 0x54, 0x50, 0x53, 0x43, 0x33, 0x1a, 0x6a, 0x2a,
	0xc8, 0x3a, 0x36, 0x40, 0xf6, 0xc1, 0x50, 0xc4, 0x43, 0x01, 0x2b, 0xa0, 0x40, 0xd5, 0x97, 0xcb,
	0x28, 0x15, 0x6a, 0x8f, 0x79, 0x07, 0x24, 0x26, 0x87, 0x52, 0x01, 0x3f, 0x02, 0x8b, 0x41, 0xc3,
	0xf5, 0x02, 0xda, 0x3d, 0x70, 0xa3, 0x61, 0xe8, 0xe9, 0x73, 0x36, 0xeb, 0x14, 0x83, 0x46, 0x4b,
	0x5a, 0x77, 0x94, 0x11, 0xde, 0x07, 0xc5, 0x09, 0x4f, 0xde, 0x49, 0xfa, 0x54, 0xad, 0x5c, 0x51,
	0xe2, 0x7e, 0x7a, 0x61, 0xb5, 0x8a, 0x52, 0x8a, 0x47, 0x13, 0xa5, 0x15, 0xf4, 0x86, 0x92, 0xa0,
	0xc2, 0x36, 0x2f, 0x86, 0x9d, 0xd5, 0x61, 0x9b, 0x53, 0x61, 0xad, 0x1f, 0x0c, 0x70, 0x6b, 0xd2,
	0xe8, 0x47, 0x44, 0x0c, 0x74, 0x5d, 0x17, 0x4f, 0xb8, 0xf1, 0x7f, 0x4f, 0xf8, 0x17, 0x20, 0x9b,
	0xf4, 0x42, 0x15, 0x5d, 0x68, 0x9a, 0x57, 0xb7, 0x48, 0x02, 0x4e, 0xfb, 0x6b, 0x17, 0xeb, 0xfb,
	0x19, 0x50, 0xba, 0x2c, 0x40, 0x78, 0x1f, 0xe4, 0x47, 0x98, 0x91, 0x3e, 0xc1, 0x8c, 0xeb, 0xdb,
	0xf8, 0xc3, 0x37, 0xe9, 0xf6, 0xa1, 0x26, 0x5f, 0x48, 0x70, 0xb2, 0x83, 0x54, 0xaa, 0x18, 0x30,
	0xcc, 0x07, 0x34, 0xe8, 0xa9, 0x1c, 0x8b, 0xce, 0xb9, 0x41, 0x6a, 0x20, 0x44, 0x87, 0x2e, 0x43,
	0x22, 0x99, 0x47, 0xde, 0x99, 0x0b, 0xd1, 0xa1, 0x83, 0x04, 0x86, 0x1f, 0x83, 0x45, 0x86, 0xbb,
	0x74, 0x84, 0xd9, 0xd8, 0x7d, 0x4c, 0xa2, 0x1e, 0x7d, 0xac, 0x1b, 0xbc, 0x90, 0x9a, 0x1f, 0x29,
	0x2b, 0x74, 0x40, 0x4e, 0xbe, 0x12, 0xea, 0xf5, 0x48, 0x6f, 0x97, 0x7f, 0x7d, 0x3d, 0x56, 0x65,
	0x92, 0x7f, 0x9f, 0x54, 0x16, 0xc7, 0x28, 0x0c, 0xee, 0x59, 0xa9, 0xa3, 0x95, 0xe4, 0x3d, 0x27,
	0xd7, 0xdb, 0x18, 0x5b, 0x23, 0x00, 0xaf, 0x56, 0x08, 0x9b, 0x60, 0x0e, 0x25, 0x17, 0xf6, 0x5b,
	0x9f, 0x80, 0x94, 0x08, 0xd7, 0x40, 0x36, 0x1e, 0x7a, 0x07, 0x78, 0xac, 0x07, 0xb4, 0x74, 0x45,
	0x6f, 0x1b, 0xd1, 0xd8, 0xd1, 0x9c, 0xd6, 0xce, 0xf1, 0x1f, 0xe5, 0xcc, 0xf3, 0xd3, 0xb2, 0x71,
	0x7c, 0x5a, 0x36, 0x5e, 0x9e, 0x96, 0x8d, 0xdf, 0x4f, 0xcb, 0xc6, 0xd1, 0x59, 0x39, 0xf3, 0xf2,
	0xac, 0x9c, 0xf9, 0xed, 0xac, 0x9c, 0xf9, 0x66, 0x6d, 0xea, 0xd9, 0x93, 0x33, 0x21, 0x68, 0x3d,
	0x40, 0x1e, 0xaf, 0x3f, 0xd8, 0x55, 0xbf, 0x22, 0x0e, 0xd3, 0xdf, 0x11, 0xea, 0x01, 0xf4, 0xb2,
	0x2a, 0xca, 0x27, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x52, 0xe7, 0xa4, 0xbb, 0x65, 0x08, 0x00,
	0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.RegistrationFee) != len(that1.RegistrationFee) {
		return false
	}
	for i := range this.RegistrationFee {
		if !this.RegistrationFee[i].Equal(&that1.RegistrationFee[i]) {
			return false
		}
	}
	return true
}
func (this *BridgeConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BridgeConfig)
	if !ok {
		that2, ok := that.(BridgeConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Challenger != that1.Challenger {
		return false
	}
	if this.Proposer != that1.Proposer {
		return false
	}
	if !this.BatchInfo.Equal(&that1.BatchInfo) {
		return false
	}
	if this.SubmissionInterval != that1.SubmissionInterval {
		return false
	}
	if this.FinalizationPeriod != that1.FinalizationPeriod {
		return false
	}
	if this.SubmissionStartHeight != that1.SubmissionStartHeight {
		return false
	}
	if this.OracleEnabled != that1.OracleEnabled {
		return false
	}
	if !bytes.Equal(this.Metadata, that1.Metadata) {
		return false
	}
	if !this.FastBridgeConfig.Equal(that1.FastBridgeConfig) {
		return false
	}
	return true
}
func (this *BatchInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BatchInfo)
	if !ok {
		that2, ok := that.(BatchInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Submitter != that1.Submitter {
		return false
	}
	if this.ChainType != that1.ChainType {
		return false
	}
	return true
}
func (this *TokenPair) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TokenPair)
	if !ok {
		that2, ok := that.(TokenPair)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.L1Denom != that1.L1Denom {
		return false
	}
	if this.L2Denom != that1.L2Denom {
		return false
	}
	return true
}
func (this *Output) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Output)
	if !ok {
		that2, ok := that.(Output)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.OutputRoot, that1.OutputRoot) {
		return false
	}
	if this.L1BlockNumber != that1.L1BlockNumber {
		return false
	}
	if !this.L1BlockTime.Equal(that1.L1BlockTime) {
		return false
	}
	if this.L2BlockNumber != that1.L2BlockNumber {
		return false
	}
	return true
}
func (this *BatchInfoWithOutput) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BatchInfoWithOutput)
	if !ok {
		that2, ok := that.(BatchInfoWithOutput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.BatchInfo.Equal(&that1.BatchInfo) {
		return false
	}
	if !this.Output.Equal(&that1.Output) {
		return false
	}
	return true
}
func (this *FastBridgeConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FastBridgeConfig)
	if !ok {
		that2, ok := that.(FastBridgeConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Verifiers) != len(that1.Verifiers) {
		return false
	}
	for i := range this.Verifiers {
		if !this.Verifiers[i].Equal(&that1.Verifiers[i]) {
			return false
		}
	}
	if this.Threshold != that1.Threshold {
		return false
	}
	if this.MaxRate != that1.MaxRate {
		return false
	}
	if this.RecoveryWindow != that1.RecoveryWindow {
		return false
	}
	if !this.BaseFee.Equal(&that1.BaseFee) {
		return false
	}
	return true
}
func (this *FastBridgeVerifier) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FastBridgeVerifier)
	if !ok {
		that2, ok := that.(FastBridgeVerifier)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	if !this.Pubkey.Equal(that1.Pubkey) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RegistrationFee) > 0 {
		for iNdEx := len(m.RegistrationFee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegistrationFee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *BridgeConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BridgeConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BridgeConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FastBridgeConfig != nil {
		{
			size, err := m.FastBridgeConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x42
	}
	if m.OracleEnabled {
		i--
		if m.OracleEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.SubmissionStartHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SubmissionStartHeight))
		i--
		dAtA[i] = 0x30
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.FinalizationPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.FinalizationPeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTypes(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.SubmissionInterval, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.SubmissionInterval):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintTypes(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x22
	{
		size, err := m.BatchInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Proposer) > 0 {
		i -= len(m.Proposer)
		copy(dAtA[i:], m.Proposer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Proposer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Challenger) > 0 {
		i -= len(m.Challenger)
		copy(dAtA[i:], m.Challenger)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Challenger)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BatchInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ChainType != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ChainType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TokenPair) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TokenPair) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TokenPair) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.L2Denom) > 0 {
		i -= len(m.L2Denom)
		copy(dAtA[i:], m.L2Denom)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.L2Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.L1Denom) > 0 {
		i -= len(m.L1Denom)
		copy(dAtA[i:], m.L1Denom)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.L1Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Output) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Output) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Output) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.L2BlockNumber != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.L2BlockNumber))
		i--
		dAtA[i] = 0x20
	}
	n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.L1BlockTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.L1BlockTime):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintTypes(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x1a
	if m.L1BlockNumber != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.L1BlockNumber))
		i--
		dAtA[i] = 0x10
	}
	if len(m.OutputRoot) > 0 {
		i -= len(m.OutputRoot)
		copy(dAtA[i:], m.OutputRoot)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OutputRoot)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BatchInfoWithOutput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BatchInfoWithOutput) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BatchInfoWithOutput) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Output.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.BatchInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FastBridgeConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FastBridgeConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FastBridgeConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BaseFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.RecoveryWindow != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RecoveryWindow))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MaxRate) > 0 {
		i -= len(m.MaxRate)
		copy(dAtA[i:], m.MaxRate)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MaxRate)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Threshold != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Threshold))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Verifiers) > 0 {
		for iNdEx := len(m.Verifiers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Verifiers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *FastBridgeVerifier) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FastBridgeVerifier) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FastBridgeVerifier) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pubkey != nil {
		{
			size, err := m.Pubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RegistrationFee) > 0 {
		for _, e := range m.RegistrationFee {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *BridgeConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Challenger)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Proposer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.BatchInfo.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.SubmissionInterval)
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.FinalizationPeriod)
	n += 1 + l + sovTypes(uint64(l))
	if m.SubmissionStartHeight != 0 {
		n += 1 + sovTypes(uint64(m.SubmissionStartHeight))
	}
	if m.OracleEnabled {
		n += 2
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.FastBridgeConfig != nil {
		l = m.FastBridgeConfig.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *BatchInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ChainType != 0 {
		n += 1 + sovTypes(uint64(m.ChainType))
	}
	return n
}

func (m *TokenPair) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.L1Denom)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.L2Denom)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *Output) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OutputRoot)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.L1BlockNumber != 0 {
		n += 1 + sovTypes(uint64(m.L1BlockNumber))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.L1BlockTime)
	n += 1 + l + sovTypes(uint64(l))
	if m.L2BlockNumber != 0 {
		n += 1 + sovTypes(uint64(m.L2BlockNumber))
	}
	return n
}

func (m *BatchInfoWithOutput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BatchInfo.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.Output.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *FastBridgeConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Verifiers) > 0 {
		for _, e := range m.Verifiers {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Threshold != 0 {
		n += 1 + sovTypes(uint64(m.Threshold))
	}
	l = len(m.MaxRate)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RecoveryWindow != 0 {
		n += 1 + sovTypes(uint64(m.RecoveryWindow))
	}
	l = m.BaseFee.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *FastBridgeVerifier) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Pubkey != nil {
		l = m.Pubkey.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistrationFee = append(m.RegistrationFee, types.Coin{})
			if err := m.RegistrationFee[len(m.RegistrationFee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BridgeConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BridgeConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BridgeConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Challenger", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Challenger = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BatchInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmissionInterval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.SubmissionInterval, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizationPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.FinalizationPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmissionStartHeight", wireType)
			}
			m.SubmissionStartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmissionStartHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OracleEnabled = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = append(m.Metadata[:0], dAtA[iNdEx:postIndex]...)
			if m.Metadata == nil {
				m.Metadata = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FastBridgeConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FastBridgeConfig == nil {
				m.FastBridgeConfig = &FastBridgeConfig{}
			}
			if err := m.FastBridgeConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainType", wireType)
			}
			m.ChainType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainType |= BatchInfo_ChainType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TokenPair) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TokenPair: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TokenPair: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L1Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L2Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L2Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Output) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Output: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Output: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutputRoot = append(m.OutputRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.OutputRoot == nil {
				m.OutputRoot = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1BlockNumber", wireType)
			}
			m.L1BlockNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.L1BlockNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1BlockTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.L1BlockTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field L2BlockNumber", wireType)
			}
			m.L2BlockNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.L2BlockNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BatchInfoWithOutput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BatchInfoWithOutput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BatchInfoWithOutput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BatchInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Output", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Output.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FastBridgeConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FastBridgeConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FastBridgeConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verifiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Verifiers = append(m.Verifiers, FastBridgeVerifier{})
			if err := m.Verifiers[len(m.Verifiers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threshold", wireType)
			}
			m.Threshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Threshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecoveryWindow", wireType)
			}
			m.RecoveryWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecoveryWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FastBridgeVerifier) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FastBridgeVerifier: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FastBridgeVerifier: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pubkey == nil {
				m.Pubkey = &types1.Any{}
			}
			if err := m.Pubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
