package types

// Rollup module event types
const (
	EventTypeAddValidator            = "add_validator"
	EventTypeRemoveValidator         = "remove_validator"
	EventTypeAddFeeWhitelist         = "add_fee_whitelist"
	EventTypeRemoveFeeWhitelist      = "remove_fee_whitelist"
	EventTypeAddBridgeExecutor       = "add_bridge_executor"
	EventTypeRemoveBridgeExecutor    = "remove_bridge_executor"
	EventTypeUpdateMinGasPrices      = "update_min_gas_prices"
	EventTypeUpdateAdmin             = "update_admin"
	EventTypeFinalizeTokenDeposit    = "finalize_token_deposit"
	EventTypeInitiateTokenWithdrawal = "initiate_token_withdrawal"
	EventTypeExecuteMessages         = "execute_messages"
	EventTypeWhitelist               = "whitelist"
	EventTypeParams                  = "params"
	EventTypeUpdateOracle            = "update_oracle"
	EventTypeSetBridgeInfo           = "set_bridge_info"
	EventTypeRegisterMigrationInfo   = "register_migration_info"
	EventTypeMigrateToken            = "migrate_token"
	EventTypeAttestorSetUpdate       = "attestor_set_update"
	EventTypeOracleDataRelay         = "oracle_data_relay"
	EventTypePacket                  = "opchild_packet"
	EventTypeTimeout                 = "timeout"

	AttributeKeySender          = "sender"
	AttributeKeyBridgeId        = "bridge_id"
	AttributeKeyBridgeAddr      = "bridge_addr"
	AttributeKeyL1ChainId       = "l1_chain_id"
	AttributeKeyL1ClientId      = "l1_client_id"
	AttributeKeyRecipient       = "recipient"
	AttributeKeyAmount          = "amount"
	AttributeKeyDenom           = "denom"
	AttributeKeySuccess         = "success"
	AttributeKeyReason          = "reason"
	AttributeKeyBaseDenom       = "base_denom"
	AttributeKeyStructTag       = "struct_tag"
	AttributeKeyValidator       = "validator"
	AttributeKeyAuthority       = "authority"
	AttributeKeyMinGasPrices    = "min_gas_prices"
	AttributeNewAdmin           = "new_admin"
	AttributeKeyMetadata        = "metadata"
	AttributeKeyL1Sequence      = "l1_sequence"
	AttributeKeyFinalizeHeight  = "finalize_height"
	AttributeKeyFrom            = "from"
	AttributeKeyTo              = "to"
	AttributeKeyL2Sequence      = "l2_sequence"
	AttributeKeyHeight          = "height"
	AttributeKeyIbcChannelId    = "ibc_channel_id"
	AttributeKeyIbcPortId       = "ibc_port_id"
	AttributeKeyIbcDenom        = "ibc_denom"
	AttributeKeyMigratedCoin    = "migrated_coin"
	AttributeKeyL1BlockHeight   = "l1_block_height"
	AttributeKeyAttestorSetSize = "attestor_set_size"
	AttributeKeyNumCurrencyPair = "num_currency_pair"
)
