// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: opinit/opchild/v1/types.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	types2 "github.com/cometbft/cometbft/abci/types"
	_ "github.com/cosmos/cosmos-proto"
	types1 "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	types3 "github.com/initia-labs/OPinit/x/ophost/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ResponseResultType defines the possible outcomes of the execution of a message
type ResponseResultType int32

const (
	// Default zero value enumeration
	UNSPECIFIED ResponseResultType = 0
	// The message did not execute msg operation (because, for example, deposit had already been finalized)
	NOOP ResponseResultType = 1
	// The message was executed successfully
	SUCCESS ResponseResultType = 2
)

var ResponseResultType_name = map[int32]string{
	0: "RESPONSE_RESULT_TYPE_UNSPECIFIED",
	1: "RESPONSE_RESULT_TYPE_NOOP",
	2: "RESPONSE_RESULT_TYPE_SUCCESS",
}

var ResponseResultType_value = map[string]int32{
	"RESPONSE_RESULT_TYPE_UNSPECIFIED": 0,
	"RESPONSE_RESULT_TYPE_NOOP":        1,
	"RESPONSE_RESULT_TYPE_SUCCESS":     2,
}

func (x ResponseResultType) String() string {
	return proto.EnumName(ResponseResultType_name, int32(x))
}

func (ResponseResultType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc6df244b706d68, []int{0}
}

// Params defines the set of opchild parameters.
type Params struct {
	// max_validators is the maximum number of validators.
	MaxValidators uint32 `protobuf:"varint,1,opt,name=max_validators,json=maxValidators,proto3" json:"max_validators,omitempty" yaml:"max_validators"`
	// historical_entries is the number of historical entries to persist.
	HistoricalEntries uint32                                      `protobuf:"varint,2,opt,name=historical_entries,json=historicalEntries,proto3" json:"historical_entries,omitempty" yaml:"historical_entries"`
	MinGasPrices      github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,3,rep,name=min_gas_prices,json=minGasPrices,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"min_gas_prices" yaml:"min_gas_price"`
	// the account address of bridge executor who can execute permissioned bridge
	// messages.
	BridgeExecutors []string `protobuf:"bytes,4,rep,name=bridge_executors,json=bridgeExecutors,proto3" json:"bridge_executors,omitempty" yaml:"bridge_executors"`
	// the account address of admin who can execute permissioned cosmos messages.
	Admin string `protobuf:"bytes,5,opt,name=admin,proto3" json:"admin,omitempty" yaml:"admin"`
	// the list of addresses that are allowed to pay zero fee.
	FeeWhitelist []string `protobuf:"bytes,6,rep,name=fee_whitelist,json=feeWhitelist,proto3" json:"fee_whitelist,omitempty" yaml:"fee_whitelist"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc6df244b706d68, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// Validator defines a validator, together with the total amount of the
// Validator's bond shares and their exchange rate to coins. Slashing results in
// a decrease in the exchange rate, allowing correct calculation of future
// undelegations without iterating over delegators. When coins are delegated to
// this validator, the validator is credited with a delegation whose number of
// bond shares is based on the amount of coins delegated divided by the current
// exchange rate. Voting power can be calculated as total bonded shares
// multiplied by exchange rate.
type Validator struct {
	Moniker string `protobuf:"bytes,1,opt,name=moniker,proto3" json:"moniker,omitempty" yaml:"moniker"`
	// operator_address defines the address of the validator's operator;
	// bech encoded in JSON.
	OperatorAddress string `protobuf:"bytes,2,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty" yaml:"operator_address"`
	// consensus_pubkey is the consensus public key of the validator,
	// as a Protobuf Any.
	ConsensusPubkey *types1.Any `protobuf:"bytes,3,opt,name=consensus_pubkey,json=consensusPubkey,proto3" json:"consensus_pubkey,omitempty" yaml:"consensus_pubkey"`
	ConsPower       int64       `protobuf:"varint,4,opt,name=cons_power,json=consPower,proto3" json:"cons_power,omitempty" yaml:"cons_power"`
}

func (m *Validator) Reset()      { *m = Validator{} }
func (*Validator) ProtoMessage() {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc6df244b706d68, []int{1}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return m.Size()
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

// ValidatorUpdates defines an array of abci.ValidatorUpdate objects.
// TODO: explore moving this to proto/cosmos/base to separate modules
// from tendermint dependence
type ValidatorUpdates struct {
	Updates []types2.ValidatorUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates"`
}

func (m *ValidatorUpdates) Reset()         { *m = ValidatorUpdates{} }
func (m *ValidatorUpdates) String() string { return proto.CompactTextString(m) }
func (*ValidatorUpdates) ProtoMessage()    {}
func (*ValidatorUpdates) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc6df244b706d68, []int{2}
}
func (m *ValidatorUpdates) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorUpdates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorUpdates.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorUpdates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorUpdates.Merge(m, src)
}
func (m *ValidatorUpdates) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorUpdates) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorUpdates.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorUpdates proto.InternalMessageInfo

// BridgeInfo defines the information of the bridge.
type BridgeInfo struct {
	// bridge id is the unique identifier of the bridge which is assigned from l1.
	BridgeId uint64 `protobuf:"varint,1,opt,name=bridge_id,json=bridgeId,proto3" json:"bridge_id,omitempty"`
	// bridge_addr is the address of the bridge on l1.
	BridgeAddr string `protobuf:"bytes,2,opt,name=bridge_addr,json=bridgeAddr,proto3" json:"bridge_addr,omitempty"`
	// l1_chain_id is the chain id of the l1 chain.
	L1ChainId string `protobuf:"bytes,3,opt,name=l1_chain_id,json=l1ChainId,proto3" json:"l1_chain_id,omitempty"`
	// l1_client_id is the IBC client ID, which is allocated for l1 chain, in l2 chain state.
	// This is used to verify the validator set in oracle update messages.
	L1ClientId string `protobuf:"bytes,4,opt,name=l1_client_id,json=l1ClientId,proto3" json:"l1_client_id,omitempty"`
	// bridge_config is the configuration of the bridge.
	BridgeConfig types3.BridgeConfig `protobuf:"bytes,5,opt,name=bridge_config,json=bridgeConfig,proto3" json:"bridge_config"`
}

func (m *BridgeInfo) Reset()         { *m = BridgeInfo{} }
func (m *BridgeInfo) String() string { return proto.CompactTextString(m) }
func (*BridgeInfo) ProtoMessage()    {}
func (*BridgeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc6df244b706d68, []int{3}
}
func (m *BridgeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BridgeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BridgeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BridgeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeInfo.Merge(m, src)
}
func (m *BridgeInfo) XXX_Size() int {
	return m.Size()
}
func (m *BridgeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeInfo proto.InternalMessageInfo

// PendingDeposits defines the set of pending deposits.
type PendingDeposits struct {
	// recipient is the address of the recipient.
	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// coins is a list of coins to be deposited.
	Coins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=coins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"coins"`
}

func (m *PendingDeposits) Reset()         { *m = PendingDeposits{} }
func (m *PendingDeposits) String() string { return proto.CompactTextString(m) }
func (*PendingDeposits) ProtoMessage()    {}
func (*PendingDeposits) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc6df244b706d68, []int{4}
}
func (m *PendingDeposits) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingDeposits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingDeposits.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingDeposits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingDeposits.Merge(m, src)
}
func (m *PendingDeposits) XXX_Size() int {
	return m.Size()
}
func (m *PendingDeposits) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingDeposits.DiscardUnknown(m)
}

var xxx_messageInfo_PendingDeposits proto.InternalMessageInfo

// CoinsWrapper defines the set of coins.
type CoinsWrapper struct {
	Coins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=coins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"coins"`
}

func (m *CoinsWrapper) Reset()         { *m = CoinsWrapper{} }
func (m *CoinsWrapper) String() string { return proto.CompactTextString(m) }
func (*CoinsWrapper) ProtoMessage()    {}
func (*CoinsWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc6df244b706d68, []int{5}
}
func (m *CoinsWrapper) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CoinsWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CoinsWrapper.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CoinsWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinsWrapper.Merge(m, src)
}
func (m *CoinsWrapper) XXX_Size() int {
	return m.Size()
}
func (m *CoinsWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinsWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_CoinsWrapper proto.InternalMessageInfo

type WithdrawalCommitment struct {
	Commitment []byte    `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	SubmitTime time.Time `protobuf:"bytes,5,opt,name=submit_time,json=submitTime,proto3,stdtime" json:"submit_time"`
}

func (m *WithdrawalCommitment) Reset()         { *m = WithdrawalCommitment{} }
func (m *WithdrawalCommitment) String() string { return proto.CompactTextString(m) }
func (*WithdrawalCommitment) ProtoMessage()    {}
func (*WithdrawalCommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc6df244b706d68, []int{6}
}
func (m *WithdrawalCommitment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WithdrawalCommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WithdrawalCommitment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WithdrawalCommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawalCommitment.Merge(m, src)
}
func (m *WithdrawalCommitment) XXX_Size() int {
	return m.Size()
}
func (m *WithdrawalCommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawalCommitment.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawalCommitment proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("opinit.opchild.v1.ResponseResultType", ResponseResultType_name, ResponseResultType_value)
	proto.RegisterType((*Params)(nil), "opinit.opchild.v1.Params")
	proto.RegisterType((*Validator)(nil), "opinit.opchild.v1.Validator")
	proto.RegisterType((*ValidatorUpdates)(nil), "opinit.opchild.v1.ValidatorUpdates")
	proto.RegisterType((*BridgeInfo)(nil), "opinit.opchild.v1.BridgeInfo")
	proto.RegisterType((*PendingDeposits)(nil), "opinit.opchild.v1.PendingDeposits")
	proto.RegisterType((*CoinsWrapper)(nil), "opinit.opchild.v1.CoinsWrapper")
	proto.RegisterType((*WithdrawalCommitment)(nil), "opinit.opchild.v1.WithdrawalCommitment")
}

func init() { proto.RegisterFile("opinit/opchild/v1/types.proto", fileDescriptor_2cc6df244b706d68) }

var fileDescriptor_2cc6df244b706d68 = []byte{
	// 1156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xbf, 0x6f, 0xdb, 0x46,
	0x14, 0x16, 0x63, 0xe5, 0x87, 0x4e, 0xb2, 0x2d, 0x1f, 0x1c, 0x54, 0x96, 0x13, 0x52, 0xe0, 0x52,
	0x21, 0xad, 0x29, 0x28, 0x69, 0x8a, 0xd6, 0x53, 0x43, 0x45, 0x29, 0xdc, 0x04, 0xb6, 0x40, 0xd9,
	0x0d, 0x9a, 0x85, 0x38, 0x92, 0x67, 0xe9, 0x10, 0x92, 0x47, 0xf0, 0x4e, 0x8e, 0xb5, 0x76, 0x0a,
	0xbc, 0x34, 0x63, 0x97, 0x00, 0x01, 0xba, 0xa4, 0x99, 0x52, 0xa0, 0x5b, 0xff, 0x81, 0xa0, 0x40,
	0x81, 0xa0, 0x53, 0x27, 0xa5, 0x75, 0x86, 0x74, 0xd6, 0xd0, 0xb9, 0xb8, 0xe3, 0xe9, 0x47, 0x9c,
	0x04, 0xe9, 0xd2, 0xc5, 0xbe, 0x7b, 0xdf, 0xf7, 0xde, 0xbb, 0xfb, 0xde, 0x7b, 0x47, 0x81, 0x8b,
	0x34, 0x21, 0x31, 0xe1, 0x0d, 0x9a, 0xf8, 0x7d, 0x12, 0x06, 0x8d, 0x83, 0x66, 0x83, 0x0f, 0x13,
	0xcc, 0xac, 0x24, 0xa5, 0x9c, 0xc2, 0x95, 0x0c, 0xb6, 0x14, 0x6c, 0x1d, 0x34, 0xab, 0x2b, 0x28,
	0x22, 0x31, 0x6d, 0xc8, 0xbf, 0x19, 0xab, 0xaa, 0xfb, 0x94, 0x45, 0x94, 0x35, 0x3c, 0xc4, 0x70,
	0xe3, 0xa0, 0xe9, 0x61, 0x8e, 0x9a, 0x0d, 0x9f, 0x92, 0x58, 0xe1, 0x6b, 0x19, 0xee, 0xca, 0x5d,
	0x23, 0xdb, 0x28, 0x68, 0xb5, 0x47, 0x7b, 0x34, 0xb3, 0x8b, 0xd5, 0xc4, 0xa1, 0x47, 0x69, 0x2f,
	0xc4, 0x0d, 0xb9, 0xf3, 0x06, 0xfb, 0x0d, 0x14, 0x0f, 0x15, 0x64, 0x9c, 0x84, 0x38, 0x89, 0x30,
	0xe3, 0x28, 0x4a, 0x14, 0xe1, 0xc2, 0xf4, 0x46, 0x7d, 0xca, 0xf8, 0x89, 0x0b, 0x55, 0xd7, 0x39,
	0x8e, 0x03, 0x9c, 0x46, 0x24, 0xe6, 0x0d, 0xe4, 0xf9, 0x64, 0x1e, 0x34, 0x7f, 0xcb, 0x83, 0x33,
	0x1d, 0x94, 0xa2, 0x88, 0xc1, 0x2f, 0xc0, 0x52, 0x84, 0x0e, 0xdd, 0x03, 0x14, 0x92, 0x00, 0x71,
	0x9a, 0xb2, 0x8a, 0x56, 0xd3, 0xea, 0x8b, 0xf6, 0xda, 0x78, 0x64, 0x9c, 0x1f, 0xa2, 0x28, 0xdc,
	0x34, 0x5f, 0xc7, 0x4d, 0x67, 0x31, 0x42, 0x87, 0x5f, 0x4f, 0xf7, 0xf0, 0x16, 0x80, 0x7d, 0xc2,
	0x38, 0x4d, 0x89, 0x8f, 0x42, 0x17, 0xc7, 0x3c, 0x25, 0x98, 0x55, 0x4e, 0xc9, 0x28, 0x17, 0xc7,
	0x23, 0x63, 0x2d, 0x8b, 0xf2, 0x26, 0xc7, 0x74, 0x56, 0x66, 0xc6, 0x76, 0x66, 0x83, 0xdf, 0x69,
	0x60, 0x29, 0x22, 0xb1, 0xdb, 0x43, 0x42, 0x46, 0xe2, 0x63, 0x56, 0x59, 0xa8, 0x2d, 0xd4, 0x8b,
	0x97, 0x2f, 0x58, 0x4a, 0x4f, 0x21, 0xbe, 0xa5, 0xc4, 0xb7, 0xae, 0x63, 0xbf, 0x45, 0x49, 0x6c,
	0xdf, 0x7c, 0x36, 0x32, 0x72, 0xe3, 0x91, 0xb1, 0xaa, 0x8e, 0x3c, 0x1f, 0xc1, 0x7c, 0xf2, 0xc2,
	0xf8, 0xa8, 0x47, 0x78, 0x7f, 0xe0, 0x59, 0x3e, 0x8d, 0x54, 0x5d, 0xd4, 0xbf, 0x0d, 0x16, 0xdc,
	0x55, 0xda, 0xa8, 0x58, 0xcc, 0x29, 0x45, 0x24, 0xfe, 0x12, 0xb1, 0x8e, 0x4c, 0x0f, 0x7d, 0x50,
	0xf6, 0x52, 0x12, 0xf4, 0xb0, 0x8b, 0x0f, 0xb1, 0x3f, 0x90, 0x1a, 0xe5, 0x6b, 0x0b, 0xf5, 0x82,
	0xfd, 0xd9, 0x78, 0x64, 0x7c, 0x90, 0x25, 0x3c, 0xc9, 0x30, 0x7f, 0xff, 0x79, 0x63, 0x55, 0x1d,
	0xf8, 0x5a, 0x10, 0xa4, 0x98, 0xb1, 0x2e, 0x4f, 0x49, 0xdc, 0x7b, 0xfc, 0xea, 0xe9, 0x25, 0xcd,
	0x59, 0xce, 0xf8, 0xed, 0x09, 0x1d, 0xb6, 0xc0, 0x69, 0x14, 0x44, 0x24, 0xae, 0x9c, 0xae, 0x69,
	0xf5, 0x82, 0xbd, 0x31, 0x1e, 0x19, 0xa5, 0x2c, 0xb2, 0x34, 0xbf, 0x27, 0x5c, 0xe6, 0x0b, 0xef,
	0x80, 0xc5, 0x7d, 0x8c, 0xdd, 0x7b, 0x7d, 0xc2, 0x71, 0x48, 0x18, 0xaf, 0x9c, 0x91, 0xc7, 0xbc,
	0x3a, 0xd3, 0xe5, 0x35, 0xf8, 0x3d, 0x41, 0x4b, 0xfb, 0x18, 0xdf, 0x9e, 0x70, 0x37, 0xd7, 0xbf,
	0x7f, 0x64, 0xe4, 0xfe, 0x7e, 0x64, 0x68, 0x47, 0xaf, 0x9e, 0x5e, 0x5a, 0x9a, 0x4c, 0x51, 0xd6,
	0x44, 0xe6, 0x2f, 0xa7, 0x40, 0x61, 0xda, 0x11, 0xf0, 0x63, 0x70, 0x36, 0xa2, 0x31, 0xb9, 0x8b,
	0x53, 0xd9, 0x4b, 0x05, 0x1b, 0x8e, 0x47, 0xc6, 0x92, 0x2a, 0x4c, 0x06, 0x98, 0xce, 0x84, 0x02,
	0x6f, 0x80, 0x32, 0x4d, 0x70, 0x2a, 0x3c, 0x5d, 0x94, 0x9d, 0x42, 0x36, 0x4f, 0xc1, 0x5e, 0x9f,
	0xc9, 0x7b, 0x92, 0x61, 0x3a, 0xcb, 0x13, 0x93, 0x3a, 0x39, 0xe4, 0xa0, 0xec, 0xd3, 0x98, 0xe1,
	0x98, 0x0d, 0x98, 0x9b, 0x0c, 0xbc, 0xbb, 0x78, 0x58, 0x59, 0xa8, 0x69, 0xf5, 0xe2, 0xe5, 0x55,
	0x2b, 0x1b, 0x25, 0x6b, 0x32, 0x4a, 0xd6, 0xb5, 0x78, 0x68, 0x5f, 0x99, 0x45, 0x3f, 0xe9, 0x67,
	0xfe, 0x3a, 0x13, 0xc6, 0x4f, 0x87, 0x09, 0xa7, 0x56, 0x67, 0xe0, 0xdd, 0xc4, 0x43, 0x67, 0x79,
	0x4a, 0xed, 0x48, 0x26, 0xfc, 0x04, 0x00, 0x61, 0x72, 0x13, 0x7a, 0x0f, 0xa7, 0x95, 0x7c, 0x4d,
	0xab, 0x2f, 0xd8, 0xe7, 0xc7, 0x23, 0x63, 0x65, 0x16, 0x39, 0xc3, 0x4c, 0xa7, 0x20, 0x36, 0x1d,
	0xb1, 0xde, 0x2c, 0xdd, 0x7f, 0x64, 0xe4, 0x94, 0xa0, 0x39, 0xd3, 0x05, 0xe5, 0xa9, 0x78, 0x7b,
	0x49, 0x80, 0x38, 0x66, 0xb0, 0x0d, 0xce, 0x0e, 0xb2, 0x65, 0x45, 0x93, 0xed, 0x5f, 0xb3, 0x66,
	0x03, 0x6d, 0x89, 0x81, 0xb6, 0x4e, 0xf8, 0xd8, 0x05, 0x31, 0x02, 0x59, 0xe9, 0x26, 0xbe, 0x9b,
	0x79, 0x99, 0xe0, 0x1f, 0x0d, 0x00, 0x5b, 0x36, 0xdc, 0x56, 0xbc, 0x4f, 0xe1, 0x3a, 0x28, 0xa8,
	0x76, 0x25, 0x81, 0xac, 0x50, 0xde, 0x39, 0x97, 0x19, 0xb6, 0x02, 0xf8, 0x39, 0x28, 0x2a, 0x50,
	0x48, 0xad, 0x2a, 0x51, 0x79, 0x57, 0xa7, 0x38, 0x20, 0x23, 0x0b, 0x23, 0xd4, 0x41, 0x31, 0x6c,
	0xba, 0x7e, 0x1f, 0x91, 0x58, 0x44, 0x16, 0xe2, 0x17, 0x9c, 0x42, 0xd8, 0x6c, 0x09, 0xcb, 0x56,
	0x00, 0x6b, 0xa0, 0x24, 0xf0, 0x90, 0xe0, 0x98, 0x0b, 0x42, 0x5e, 0x12, 0x40, 0xd8, 0x6c, 0x49,
	0xd3, 0x56, 0x00, 0xb7, 0xc1, 0xa2, 0x4a, 0xee, 0xd3, 0x78, 0x9f, 0xf4, 0xe4, 0x34, 0x14, 0x2f,
	0xeb, 0xd6, 0xf4, 0x75, 0x16, 0x4f, 0x9d, 0x75, 0xd0, 0xb4, 0xb2, 0xeb, 0xb4, 0x24, 0x6b, 0xfe,
	0xe6, 0x25, 0x6f, 0x0e, 0x30, 0x7f, 0xd2, 0xc0, 0x72, 0x07, 0xc7, 0x01, 0x89, 0x7b, 0xd7, 0x71,
	0x42, 0x19, 0xe1, 0x0c, 0x7e, 0x0a, 0x0a, 0x29, 0xf6, 0x49, 0x22, 0x52, 0xaa, 0xfe, 0x7c, 0xf7,
	0xf5, 0x66, 0x54, 0xb8, 0x0f, 0x4e, 0x8b, 0x97, 0x5e, 0x34, 0xa7, 0xa8, 0xc7, 0xda, 0x5b, 0x9f,
	0x23, 0xf9, 0x16, 0x5d, 0x15, 0xc7, 0x79, 0xf2, 0xc2, 0xa8, 0xff, 0x87, 0x37, 0x47, 0x3e, 0x38,
	0x6a, 0x88, 0x65, 0x78, 0xf3, 0x00, 0x94, 0xa4, 0xf1, 0x76, 0x8a, 0x92, 0x04, 0xa7, 0xb3, 0xbc,
	0xda, 0xff, 0x9b, 0xf7, 0x5b, 0x0d, 0xac, 0xde, 0x26, 0xbc, 0x1f, 0xa4, 0xe8, 0x1e, 0x0a, 0x5b,
	0x34, 0x8a, 0x08, 0x8f, 0xc4, 0xc5, 0x75, 0xd1, 0xe2, 0x93, 0x9d, 0x54, 0xac, 0xe4, 0xcc, 0x59,
	0xe0, 0x57, 0xa0, 0xc8, 0x06, 0x5e, 0x44, 0xb8, 0x2b, 0xbe, 0x50, 0xaa, 0x64, 0xd5, 0x37, 0x66,
	0x6e, 0x77, 0xf2, 0xf9, 0xb2, 0x17, 0xc5, 0x39, 0x1f, 0xbc, 0x30, 0xb4, 0x2c, 0x3f, 0xc8, 0xbc,
	0x05, 0x7e, 0xe9, 0x47, 0x0d, 0x40, 0x07, 0xb3, 0x44, 0x4c, 0x99, 0x83, 0xd9, 0x20, 0xe4, 0xbb,
	0xc3, 0x04, 0xc3, 0xab, 0xa0, 0xe6, 0xb4, 0xbb, 0x9d, 0x9d, 0xed, 0x6e, 0xdb, 0x75, 0xda, 0xdd,
	0xbd, 0x5b, 0xbb, 0xee, 0xee, 0x37, 0x9d, 0xb6, 0xbb, 0xb7, 0xdd, 0xed, 0xb4, 0x5b, 0x5b, 0x37,
	0xb6, 0xda, 0xd7, 0xcb, 0xb9, 0xea, 0xf2, 0xd1, 0xc3, 0x5a, 0x71, 0xce, 0x04, 0x3f, 0x04, 0x6b,
	0x6f, 0x75, 0xdb, 0xde, 0xd9, 0xe9, 0x94, 0xb5, 0xea, 0xb9, 0xa3, 0x87, 0xb5, 0xbc, 0x58, 0xc3,
	0x0d, 0x70, 0xe1, 0xad, 0xc4, 0xee, 0x5e, 0xab, 0xd5, 0xee, 0x76, 0xcb, 0xa7, 0xaa, 0xc5, 0xa3,
	0x87, 0xb5, 0xb3, 0x6a, 0x5b, 0xcd, 0xdf, 0xff, 0x41, 0xcf, 0xd9, 0x3b, 0xcf, 0xfe, 0xd2, 0x73,
	0x8f, 0x8f, 0x75, 0xed, 0xd9, 0xb1, 0xae, 0x3d, 0x3f, 0xd6, 0xb5, 0x3f, 0x8f, 0x75, 0xed, 0xc1,
	0x4b, 0x3d, 0xf7, 0xfc, 0xa5, 0x9e, 0xfb, 0xe3, 0xa5, 0x9e, 0xbb, 0xb3, 0x31, 0x57, 0x08, 0xd1,
	0xbf, 0x04, 0x6d, 0x84, 0xc8, 0x63, 0x8d, 0x9d, 0x8e, 0xfc, 0x70, 0x1f, 0x4e, 0x7f, 0x8c, 0xc8,
	0x9a, 0x78, 0x67, 0xa4, 0x56, 0x57, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xf5, 0x5f, 0xd8,
	0xab, 0x08, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxValidators != that1.MaxValidators {
		return false
	}
	if this.HistoricalEntries != that1.HistoricalEntries {
		return false
	}
	if len(this.MinGasPrices) != len(that1.MinGasPrices) {
		return false
	}
	for i := range this.MinGasPrices {
		if !this.MinGasPrices[i].Equal(&that1.MinGasPrices[i]) {
			return false
		}
	}
	if len(this.BridgeExecutors) != len(that1.BridgeExecutors) {
		return false
	}
	for i := range this.BridgeExecutors {
		if this.BridgeExecutors[i] != that1.BridgeExecutors[i] {
			return false
		}
	}
	if this.Admin != that1.Admin {
		return false
	}
	if len(this.FeeWhitelist) != len(that1.FeeWhitelist) {
		return false
	}
	for i := range this.FeeWhitelist {
		if this.FeeWhitelist[i] != that1.FeeWhitelist[i] {
			return false
		}
	}
	return true
}
func (this *BridgeInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BridgeInfo)
	if !ok {
		that2, ok := that.(BridgeInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BridgeId != that1.BridgeId {
		return false
	}
	if this.BridgeAddr != that1.BridgeAddr {
		return false
	}
	if this.L1ChainId != that1.L1ChainId {
		return false
	}
	if this.L1ClientId != that1.L1ClientId {
		return false
	}
	if !this.BridgeConfig.Equal(&that1.BridgeConfig) {
		return false
	}
	return true
}
func (this *PendingDeposits) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PendingDeposits)
	if !ok {
		that2, ok := that.(PendingDeposits)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Recipient != that1.Recipient {
		return false
	}
	if len(this.Coins) != len(that1.Coins) {
		return false
	}
	for i := range this.Coins {
		if !this.Coins[i].Equal(&that1.Coins[i]) {
			return false
		}
	}
	return true
}
func (this *CoinsWrapper) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CoinsWrapper)
	if !ok {
		that2, ok := that.(CoinsWrapper)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Coins) != len(that1.Coins) {
		return false
	}
	for i := range this.Coins {
		if !this.Coins[i].Equal(&that1.Coins[i]) {
			return false
		}
	}
	return true
}
func (this *WithdrawalCommitment) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WithdrawalCommitment)
	if !ok {
		that2, ok := that.(WithdrawalCommitment)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Commitment, that1.Commitment) {
		return false
	}
	if !this.SubmitTime.Equal(that1.SubmitTime) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeeWhitelist) > 0 {
		for iNdEx := len(m.FeeWhitelist) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FeeWhitelist[iNdEx])
			copy(dAtA[i:], m.FeeWhitelist[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.FeeWhitelist[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.BridgeExecutors) > 0 {
		for iNdEx := len(m.BridgeExecutors) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BridgeExecutors[iNdEx])
			copy(dAtA[i:], m.BridgeExecutors[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.BridgeExecutors[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.MinGasPrices) > 0 {
		for iNdEx := len(m.MinGasPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinGasPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.HistoricalEntries != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.HistoricalEntries))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxValidators != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxValidators))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Validator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Validator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Validator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ConsPower != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ConsPower))
		i--
		dAtA[i] = 0x20
	}
	if m.ConsensusPubkey != nil {
		{
			size, err := m.ConsensusPubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Moniker) > 0 {
		i -= len(m.Moniker)
		copy(dAtA[i:], m.Moniker)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Moniker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorUpdates) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorUpdates) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorUpdates) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Updates) > 0 {
		for iNdEx := len(m.Updates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Updates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *BridgeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BridgeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BridgeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BridgeConfig.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.L1ClientId) > 0 {
		i -= len(m.L1ClientId)
		copy(dAtA[i:], m.L1ClientId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.L1ClientId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.L1ChainId) > 0 {
		i -= len(m.L1ChainId)
		copy(dAtA[i:], m.L1ChainId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.L1ChainId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BridgeAddr) > 0 {
		i -= len(m.BridgeAddr)
		copy(dAtA[i:], m.BridgeAddr)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BridgeAddr)))
		i--
		dAtA[i] = 0x12
	}
	if m.BridgeId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BridgeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PendingDeposits) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingDeposits) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingDeposits) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Coins) > 0 {
		for iNdEx := len(m.Coins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Coins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CoinsWrapper) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CoinsWrapper) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CoinsWrapper) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Coins) > 0 {
		for iNdEx := len(m.Coins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Coins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *WithdrawalCommitment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WithdrawalCommitment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WithdrawalCommitment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.SubmitTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.SubmitTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintTypes(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x2a
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxValidators != 0 {
		n += 1 + sovTypes(uint64(m.MaxValidators))
	}
	if m.HistoricalEntries != 0 {
		n += 1 + sovTypes(uint64(m.HistoricalEntries))
	}
	if len(m.MinGasPrices) > 0 {
		for _, e := range m.MinGasPrices {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if len(m.BridgeExecutors) > 0 {
		for _, s := range m.BridgeExecutors {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.FeeWhitelist) > 0 {
		for _, s := range m.FeeWhitelist {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *Validator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Moniker)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ConsensusPubkey != nil {
		l = m.ConsensusPubkey.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ConsPower != 0 {
		n += 1 + sovTypes(uint64(m.ConsPower))
	}
	return n
}

func (m *ValidatorUpdates) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Updates) > 0 {
		for _, e := range m.Updates {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *BridgeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BridgeId != 0 {
		n += 1 + sovTypes(uint64(m.BridgeId))
	}
	l = len(m.BridgeAddr)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.L1ChainId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.L1ClientId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.BridgeConfig.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *PendingDeposits) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Coins) > 0 {
		for _, e := range m.Coins {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *CoinsWrapper) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Coins) > 0 {
		for _, e := range m.Coins {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *WithdrawalCommitment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.SubmitTime)
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxValidators", wireType)
			}
			m.MaxValidators = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxValidators |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HistoricalEntries", wireType)
			}
			m.HistoricalEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HistoricalEntries |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinGasPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinGasPrices = append(m.MinGasPrices, types.DecCoin{})
			if err := m.MinGasPrices[len(m.MinGasPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeExecutors", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BridgeExecutors = append(m.BridgeExecutors, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeWhitelist", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeWhitelist = append(m.FeeWhitelist, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Validator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moniker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moniker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusPubkey == nil {
				m.ConsensusPubkey = &types1.Any{}
			}
			if err := m.ConsensusPubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsPower", wireType)
			}
			m.ConsPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorUpdates) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorUpdates: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorUpdates: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Updates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Updates = append(m.Updates, types2.ValidatorUpdate{})
			if err := m.Updates[len(m.Updates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BridgeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BridgeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BridgeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeId", wireType)
			}
			m.BridgeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BridgeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BridgeAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L1ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field L1ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.L1ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BridgeConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingDeposits) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingDeposits: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingDeposits: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = append(m.Coins, types.Coin{})
			if err := m.Coins[len(m.Coins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CoinsWrapper) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CoinsWrapper: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CoinsWrapper: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = append(m.Coins, types.Coin{})
			if err := m.Coins[len(m.Coins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WithdrawalCommitment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WithdrawalCommitment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WithdrawalCommitment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.SubmitTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
