name: Protobuf
# Protobuf runs buf (https://buf.build/) lint and check-breakage
# This workflow is only run when a .proto file has been changed

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - "proto/**"
  release:
    types: [created, published]
  pull_request:
    paths:
      - "proto/**"

permissions:
  contents: read

jobs:
  buf-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: |
      github.event_name == 'push' && (
        github.ref == 'refs/heads/main' ||
        startsWith(github.ref, 'refs/tags/')
      ) ||
      github.event_name == 'release'
    steps:
      - uses: actions/checkout@v5
      - uses: bufbuild/buf-action@v1
        with:
          input: "proto"
          token: ${{ secrets.BUF_TOKEN }}
          format: true
          lint: true
          breaking: true
          push: false 
          breaking_against: base/proto