name: Protobuf
# Protobuf runs buf (https://buf.build/) fmt, lint and check-breakage and pushes to buf.build
# This workflow is only run when a .proto file has been changed

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - "proto/**"
  release:
    types: [created, published]
  pull_request:
    paths:
      - "proto/**"

permissions:
  contents: write

jobs:
  buf-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - uses: bufbuild/buf-action@v1
        with:
          input: proto
          token: ${{ secrets.BUF_TOKEN }}
          format: false
          lint: false
          breaking: false
          breaking_against: main/proto
          push: true
      #- run: buf push proto --error-format github-actions